# Generated by Django 4.2.6 on 2023-11-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mascota", "0002_mascota_edad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascota",
            name="fechaIngreso",
            field=models.DateField(auto_now_add=True),
        ),
    ]
